data:
  aux_edge_order: 3
  cutoff:
  cutoff_pos:
  dataset_name: geom-drug
  dset_mode: multi_sample_low
  edge_transform_mode: aux_edge
  heavy_only: true
  lowest_thres: 0.0
  processed_tag: dgl_processed
  rdkit_pos_mode: online
  test_dataset: data/icml_drug_expand/drug_test.pkl
  train_dataset: data/icml_drug_expand/drug_train_95.pkl
  val_dataset: data/icml_drug_expand/drug_val.pkl
eval:
  delta: 1.25
  eval_noise: 0.0
  eval_propose_net_type: online_rdkit
  ff_opt: false

model:
  model_type: ours_o2

ours_o2:
  num_blocks: 3
  num_layers: 3
  hidden_dim: 256
  n_heads: 16
  num_r_gaussian: 50
  num_node_types: 8
  act_fn: relu
  norm: True
  cutoff_mode: radius  # [radius, none]
  ew_net_type: global  # [r, m, global, none]
  r_feat_mode: sparse  # [basic, sparse]
  energy_h_mode: basic
  num_x2h: 1
  num_h2x: 1
  r_max: 10.
  x2h_out_fc: False
  sync_twoup: False

train:
  batch_size: 16
  beta1: 0.95
  beta2: 0.999
  grad_norm: 8.0
  gt_aug_ratio: 0.05
  lr: 0.001
  max_iters: 1000000
  min_lr: 1.0e-05
  n_acc_batch: 1
  noise_std: 0.0
  noise_type: const
  num_workers: 4
  opt_type: adam
  patience: 20
  propose_net_type: gt
  sched_factor: 0.5
  sched_patience: 8
  sched_type: plateau
  seed: 2020
  train_report_iter: 200
  val_freq: 2000
  weight_decay: 0
  loss_type: wasserstein
  n_ref_samples: 5
  n_gen_samples: 5
